/**
 * Acceptance criterion 5: progress survives a reload **and a bank reimport**.
 *
 * `store.test.ts` covers the reload. This covers the half that is easy to
 * believe and hard to check — that a backup taken today still binds to the
 * right questions after `questions.json` is regenerated, ids move and the array
 * is reordered. That property is the entire reason progress is keyed on
 * `contentHash`, and the failure mode if it breaks is silent: the user keeps
 * drilling and the history quietly belongs to the wrong questions.
 *
 * Written as `.ts` — the provider is mounted with `createElement`, no JSX.
 */
import { act, cleanup, renderHook, waitFor } from '@testing-library/react';
import { createElement, type ReactNode } from 'react';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { drillable, questionByHash, questions } from '../../lib/bank';
import { openDb, resetDbHandle, type DbDump } from '../../lib/db';
import { weakQuestions } from '../../lib/selectors';
import { StoreProvider, useStore } from '../../lib/store';
import type { Grade, Question } from '../../types';
import { disputes } from './currency';
import { buildSheet, DEFAULT_FILTERS } from './markdown';

const wrapper = ({ children }: { children: ReactNode }) =>
  createElement(StoreProvider, null, children);

const wipe = (): Promise<void> =>
  new Promise((resolve) => {
    const req = indexedDB.deleteDatabase('pl400');
    req.onsuccess = () => resolve();
    req.onerror = () => resolve();
    req.onblocked = () => resolve();
  });

const mounted = async () => {
  const view = renderHook(() => useStore(), { wrapper });
  await waitFor(() => expect(view.result.current.ready).toBe(true));
  return view;
};

const wrong: Grade = { correct: false, perBox: null, selfGraded: false, ungradeable: false };

/** Three questions spread across the bank, so position cannot be doing the work. */
const sample: Question[] = [drillable[0]!, drillable[Math.floor(drillable.length / 2)]!, drillable[drillable.length - 1]!];

beforeEach(async () => {
  resetDbHandle();
  await wipe();
});

afterEach(async () => {
  cleanup();
  (await openDb()).close();
  resetDbHandle();
});

describe('the backup is keyed on content, not on position', () => {
  it('carries no question id or array index of any kind', async () => {
    const view = await mounted();
    await act(async () => {
      for (const question of sample) {
        await view.result.current.recordAttempt({
          question,
          grade: wrong,
          confidence: 'unsure',
          elapsedMs: 1,
        });
      }
    });

    const dump = JSON.parse(await view.result.current.exportJson()) as DbDump;
    expect(dump.progress).toHaveLength(sample.length);
    for (const record of dump.progress) {
      expect(Object.keys(record).sort()).toEqual(
        ['attempts', 'box', 'contentHash', 'correction', 'dueAt', 'notes', 'timesWrong'].sort(),
      );
      expect(record.contentHash).toMatch(/\S/);
    }
  });

  /**
   * The bank is regenerated by rerunning stages 03 and 04. That can renumber
   * questions and reorder the array; it must not move anybody's history.
   */
  it('binds to the same questions after the bank is renumbered and reordered', async () => {
    const first = await mounted();
    await act(async () => {
      for (const question of sample) {
        await first.result.current.recordAttempt({
          question,
          grade: wrong,
          confidence: 'unsure',
          elapsedMs: 1,
        });
      }
      await first.result.current.setCorrection(sample[0]!.contentHash, 'Key should be C, not D.');
    });
    const backup = await first.result.current.exportJson();
    // Wiping through the store rather than deleting the database: a mid-test
    // `deleteDatabase` blocks on the provider's own open handle and hangs.
    await act(async () => {
      await first.result.current.resetAll();
    });
    first.unmount();

    // A rebuilt bank: same questions, new ids, shuffled order. Nothing in the
    // backup may depend on either.
    const rebuilt = [...questions]
      .map((q, i) => ({ ...q, id: q.id + 1000, sourcePages: [i] }))
      .reverse();
    const rebuiltByHash = new Map(rebuilt.map((q) => [q.contentHash, q]));

    const second = await mounted();
    let outcome = { imported: 0, skipped: 0 };
    await act(async () => {
      outcome = await second.result.current.importJson(backup);
    });

    expect(outcome.imported).toBe(sample.length);
    for (const question of sample) {
      const record = second.result.current.progress.get(question.contentHash);
      expect(record?.timesWrong).toBe(1);
      // Resolved against the rebuilt bank, the record still names this question.
      expect(rebuiltByHash.get(record!.contentHash)?.id).toBe(question.id + 1000);
      // …and against the shipped bank, it still names the same one.
      expect(questionByHash(record!.contentHash)).toBe(question);
    }
    expect(
      second.result.current.progress.get(sample[0]!.contentHash)?.correction,
    ).toBe('Key should be C, not D.');
  });

  it('feeds the restored history straight back into the weak list and the sheet', async () => {
    const first = await mounted();
    await act(async () => {
      for (const question of sample) {
        // Twice, so they clear the "wrong at least twice" threshold.
        await first.result.current.recordAttempt({
          question,
          grade: wrong,
          confidence: 'unsure',
          elapsedMs: 1,
        });
        await first.result.current.recordAttempt({
          question,
          grade: wrong,
          confidence: 'unsure',
          elapsedMs: 1,
        });
      }
    });
    const backup = await first.result.current.exportJson();
    await act(async () => {
      await first.result.current.resetAll();
    });
    first.unmount();

    const second = await mounted();
    await act(async () => {
      await second.result.current.importJson(backup);
    });

    const weak = weakQuestions(second.result.current.progress, { minWrong: 2 });
    for (const question of sample) expect(weak).toContain(question);

    const sheet = buildSheet(second.result.current.progress, {
      ...DEFAULT_FILTERS,
      minWrong: 2,
      limit: null,
    });
    for (const question of sample) expect(sheet.markdown).toContain(`**q${question.id}**`);
  });

  it('drops a correction whose question the new bank no longer carries', async () => {
    const view = await mounted();
    await act(async () => {
      await view.result.current.setCorrection('a-hash-no-bank-ever-produced', 'orphaned');
    });
    // Surfaced nowhere rather than crashing the disputes list.
    expect(disputes(view.result.current.progress)).toEqual([]);
  });
});
